
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.beyondmc.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.beyondmc.block.YellowredstonelamponBlock;
import net.mcreator.beyondmc.block.YellowredstonelampBlock;
import net.mcreator.beyondmc.block.WhiteredstonelamponBlock;
import net.mcreator.beyondmc.block.WhiteredstonelampBlock;
import net.mcreator.beyondmc.block.Weed3Block;
import net.mcreator.beyondmc.block.Weed2Block;
import net.mcreator.beyondmc.block.Weed1Block;
import net.mcreator.beyondmc.block.Weed0Block;
import net.mcreator.beyondmc.block.SuspiciousplanksBlock;
import net.mcreator.beyondmc.block.SuspiciouslogBlock;
import net.mcreator.beyondmc.block.SuspiciousleavesBlock;
import net.mcreator.beyondmc.block.SpaceBlock;
import net.mcreator.beyondmc.block.SkyBlock;
import net.mcreator.beyondmc.block.SilveroreBlock;
import net.mcreator.beyondmc.block.SilverbricksBlock;
import net.mcreator.beyondmc.block.RedstonelamponBlock;
import net.mcreator.beyondmc.block.RedredstonelampBlock;
import net.mcreator.beyondmc.block.PurpleredstonelamponBlock;
import net.mcreator.beyondmc.block.PurpleredstonelampBlock;
import net.mcreator.beyondmc.block.PinkredstonelamponBlock;
import net.mcreator.beyondmc.block.PinkredstonelampBlock;
import net.mcreator.beyondmc.block.OrangeredstonelamponBlock;
import net.mcreator.beyondmc.block.OrangeredstonelampBlock;
import net.mcreator.beyondmc.block.MethylamineoreBlock;
import net.mcreator.beyondmc.block.MethglassBlock;
import net.mcreator.beyondmc.block.MagentaredstonelamponBlock;
import net.mcreator.beyondmc.block.MagentaredstonelampBlock;
import net.mcreator.beyondmc.block.LimeredstonelamponBlock;
import net.mcreator.beyondmc.block.LimeredstonelampBlock;
import net.mcreator.beyondmc.block.LightgreyredstonelamponBlock;
import net.mcreator.beyondmc.block.LightgreyredstonelampBlock;
import net.mcreator.beyondmc.block.LightblueredstonelamponBlock;
import net.mcreator.beyondmc.block.LightblueredstonelampBlock;
import net.mcreator.beyondmc.block.IronbricksBlock;
import net.mcreator.beyondmc.block.GreyredstonelamponBlock;
import net.mcreator.beyondmc.block.GreyredstonelampBlock;
import net.mcreator.beyondmc.block.GreenredstonelamponBlock;
import net.mcreator.beyondmc.block.GreenredstonelampBlock;
import net.mcreator.beyondmc.block.DistilledmethblockBlock;
import net.mcreator.beyondmc.block.CyanredstonelamponBlock;
import net.mcreator.beyondmc.block.CyanredstonelampBlock;
import net.mcreator.beyondmc.block.CoreBlock;
import net.mcreator.beyondmc.block.Coke3Block;
import net.mcreator.beyondmc.block.Coke2Block;
import net.mcreator.beyondmc.block.Coke1Block;
import net.mcreator.beyondmc.block.Coke0Block;
import net.mcreator.beyondmc.block.CocainblockBlock;
import net.mcreator.beyondmc.block.BlueredstonelamponBlock;
import net.mcreator.beyondmc.block.BlueredstonelampBlock;
import net.mcreator.beyondmc.block.BlackredstonelamponBlock;
import net.mcreator.beyondmc.block.BlackredstonelampBlock;
import net.mcreator.beyondmc.BeyondmcMod;

public class BeyondmcModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, BeyondmcMod.MODID);
	public static final RegistryObject<Block> CORE = REGISTRY.register("core", () -> new CoreBlock());
	public static final RegistryObject<Block> WEED_0 = REGISTRY.register("weed_0", () -> new Weed0Block());
	public static final RegistryObject<Block> WEED_1 = REGISTRY.register("weed_1", () -> new Weed1Block());
	public static final RegistryObject<Block> WEED_2 = REGISTRY.register("weed_2", () -> new Weed2Block());
	public static final RegistryObject<Block> WEED_3 = REGISTRY.register("weed_3", () -> new Weed3Block());
	public static final RegistryObject<Block> SUSPICIOUSLEAVES = REGISTRY.register("suspiciousleaves", () -> new SuspiciousleavesBlock());
	public static final RegistryObject<Block> SUSPICIOUSLOG = REGISTRY.register("suspiciouslog", () -> new SuspiciouslogBlock());
	public static final RegistryObject<Block> COCAINBLOCK = REGISTRY.register("cocainblock", () -> new CocainblockBlock());
	public static final RegistryObject<Block> METHYLAMINEORE = REGISTRY.register("methylamineore", () -> new MethylamineoreBlock());
	public static final RegistryObject<Block> DISTILLEDMETHBLOCK = REGISTRY.register("distilledmethblock", () -> new DistilledmethblockBlock());
	public static final RegistryObject<Block> METHGLASS = REGISTRY.register("methglass", () -> new MethglassBlock());
	public static final RegistryObject<Block> SKY = REGISTRY.register("sky", () -> new SkyBlock());
	public static final RegistryObject<Block> SPACE = REGISTRY.register("space", () -> new SpaceBlock());
	public static final RegistryObject<Block> SUSPICIOUSPLANKS = REGISTRY.register("suspiciousplanks", () -> new SuspiciousplanksBlock());
	public static final RegistryObject<Block> SILVERORE = REGISTRY.register("silverore", () -> new SilveroreBlock());
	public static final RegistryObject<Block> IRONBRICKS = REGISTRY.register("ironbricks", () -> new IronbricksBlock());
	public static final RegistryObject<Block> SILVERBRICKS = REGISTRY.register("silverbricks", () -> new SilverbricksBlock());
	public static final RegistryObject<Block> REDSTONELAMPON = REGISTRY.register("redstonelampon", () -> new RedstonelamponBlock());
	public static final RegistryObject<Block> COKE_0 = REGISTRY.register("coke_0", () -> new Coke0Block());
	public static final RegistryObject<Block> COKE_1 = REGISTRY.register("coke_1", () -> new Coke1Block());
	public static final RegistryObject<Block> COKE_2 = REGISTRY.register("coke_2", () -> new Coke2Block());
	public static final RegistryObject<Block> COKE_3 = REGISTRY.register("coke_3", () -> new Coke3Block());
	public static final RegistryObject<Block> REDREDSTONELAMP = REGISTRY.register("redredstonelamp", () -> new RedredstonelampBlock());
	public static final RegistryObject<Block> BLUEREDSTONELAMP = REGISTRY.register("blueredstonelamp", () -> new BlueredstonelampBlock());
	public static final RegistryObject<Block> BLUEREDSTONELAMPON = REGISTRY.register("blueredstonelampon", () -> new BlueredstonelamponBlock());
	public static final RegistryObject<Block> PINKREDSTONELAMP = REGISTRY.register("pinkredstonelamp", () -> new PinkredstonelampBlock());
	public static final RegistryObject<Block> PINKREDSTONELAMPON = REGISTRY.register("pinkredstonelampon", () -> new PinkredstonelamponBlock());
	public static final RegistryObject<Block> LIGHTBLUEREDSTONELAMP = REGISTRY.register("lightblueredstonelamp", () -> new LightblueredstonelampBlock());
	public static final RegistryObject<Block> LIGHTBLUEREDSTONELAMPON = REGISTRY.register("lightblueredstonelampon", () -> new LightblueredstonelamponBlock());
	public static final RegistryObject<Block> PURPLEREDSTONELAMP = REGISTRY.register("purpleredstonelamp", () -> new PurpleredstonelampBlock());
	public static final RegistryObject<Block> PURPLEREDSTONELAMPON = REGISTRY.register("purpleredstonelampon", () -> new PurpleredstonelamponBlock());
	public static final RegistryObject<Block> GREENREDSTONELAMP = REGISTRY.register("greenredstonelamp", () -> new GreenredstonelampBlock());
	public static final RegistryObject<Block> GREENREDSTONELAMPON = REGISTRY.register("greenredstonelampon", () -> new GreenredstonelamponBlock());
	public static final RegistryObject<Block> YELLOWREDSTONELAMP = REGISTRY.register("yellowredstonelamp", () -> new YellowredstonelampBlock());
	public static final RegistryObject<Block> YELLOWREDSTONELAMPON = REGISTRY.register("yellowredstonelampon", () -> new YellowredstonelamponBlock());
	public static final RegistryObject<Block> MAGENTAREDSTONELAMP = REGISTRY.register("magentaredstonelamp", () -> new MagentaredstonelampBlock());
	public static final RegistryObject<Block> MAGENTAREDSTONELAMPON = REGISTRY.register("magentaredstonelampon", () -> new MagentaredstonelamponBlock());
	public static final RegistryObject<Block> LIMEREDSTONELAMP = REGISTRY.register("limeredstonelamp", () -> new LimeredstonelampBlock());
	public static final RegistryObject<Block> LIMEREDSTONELAMPON = REGISTRY.register("limeredstonelampon", () -> new LimeredstonelamponBlock());
	public static final RegistryObject<Block> ORANGEREDSTONELAMP = REGISTRY.register("orangeredstonelamp", () -> new OrangeredstonelampBlock());
	public static final RegistryObject<Block> ORANGEREDSTONELAMPON = REGISTRY.register("orangeredstonelampon", () -> new OrangeredstonelamponBlock());
	public static final RegistryObject<Block> GREYREDSTONELAMP = REGISTRY.register("greyredstonelamp", () -> new GreyredstonelampBlock());
	public static final RegistryObject<Block> GREYREDSTONELAMPON = REGISTRY.register("greyredstonelampon", () -> new GreyredstonelamponBlock());
	public static final RegistryObject<Block> CYANREDSTONELAMP = REGISTRY.register("cyanredstonelamp", () -> new CyanredstonelampBlock());
	public static final RegistryObject<Block> CYANREDSTONELAMPON = REGISTRY.register("cyanredstonelampon", () -> new CyanredstonelamponBlock());
	public static final RegistryObject<Block> WHITEREDSTONELAMP = REGISTRY.register("whiteredstonelamp", () -> new WhiteredstonelampBlock());
	public static final RegistryObject<Block> WHITEREDSTONELAMPON = REGISTRY.register("whiteredstonelampon", () -> new WhiteredstonelamponBlock());
	public static final RegistryObject<Block> LIGHTGREYREDSTONELAMP = REGISTRY.register("lightgreyredstonelamp", () -> new LightgreyredstonelampBlock());
	public static final RegistryObject<Block> LIGHTGREYREDSTONELAMPON = REGISTRY.register("lightgreyredstonelampon", () -> new LightgreyredstonelamponBlock());
	public static final RegistryObject<Block> BLACKREDSTONELAMP = REGISTRY.register("blackredstonelamp", () -> new BlackredstonelampBlock());
	public static final RegistryObject<Block> BLACKREDSTONELAMPON = REGISTRY.register("blackredstonelampon", () -> new BlackredstonelamponBlock());
}
